### PR TITLE
Rename timeout field to shardTimeout and update assoicated setter/get…

### PR DESCRIPTION
**Pull request by aaronzhongg**
- Rename timeout field to shardTimeout

- Rename timeout's getters and setters from getTimeout and setTimeout to getShardTimeout and setShardTimeout

- Update test cases to use new getters/setters

### CODE REVIEW

**Comment by jaygradon** [comment]
As I understand the issue, it desires renaming the `timeout` parameter.  Are you sure this is just the field and not a param in the REST API?

**Comment by aaronzhongg** [comment]
Thanks @jaygradon, you're right. I have now also changed the param from `timeout` to `shard_timeout` and have updated the docs accordingly

**Comment by jaygradon** [comment]
LGTM 👍 if its passing all tests

**Review by jaygradon — APPROVED** [review]

**Review by Helen-Zhao — APPROVED** [review]
Looks good to me

**Comment by aaronzhongg** [comment]
Thanks @jaygradon for reminding me to run tests, I actually missed a few spots where I had to change the param which I found after running the tests. The tests all pass now

**Pull request merged**
